In [2]:
#A Python library is a collection of pre-written code that you can use to perform common tasks without having to write the code from scratch. These libraries contain functions, classes, and modules that can be imported into your Python programs to provide additional functionality.

#Why We Use Python Libraries:
#Efficiency:

#Save Time: Libraries provide pre-written functions and classes, allowing you to avoid writing code from scratch.
#Code Reuse: Reuse existing, well-tested code, which can significantly speed up the development process.
###Functionality:

#Specialized Tools: Many libraries are designed for specific tasks such as data analysis, web development, machine learning, etc. For example, NumPy and pandas for data analysis, Flask and Django for web development, and TensorFlow and PyTorch for machine learning.
#Extended Capabilities: They extend the basic functionalities of Python, enabling you to accomplish more complex tasks that are not feasible with the standard library alone.
#Reliability:

#Well-Tested: Libraries, especially popular ones, are often well-tested and maintained by a community of developers, which ensures they are reliable and less prone to bugs.
#Community Support: Popular libraries have a large user base and community support, making it easier to find help, documentation, and tutorials.
#Consistency:

#Standard Practices: Libraries often follow standard practices and conventions, promoting consistency in your code.
#Maintenance: Using well-maintained libraries ensures that your codebase can stay updated with minimal effort.
#Examples of Popular Python Libraries:
#NumPy: For numerical computations and handling large multi-dimensional arrays and matrices.
#pandas: For data manipulation and analysis.
#Matplotlib: For data visualization and plotting.
#Requests: For making HTTP requests.
#Beautiful Soup: For web scraping and parsing HTML and XML documents.
#Flask and Django: For web development.
#TensorFlow and PyTorch: For machine learning and deep learning.
#How to Use Python Libraries:
#To use a library, you typically need to install it (if it's not included in the standard library) and then import it into your Python script. For example:

In [5]:
##What is a Python library? Why ^o we use Python libraries?
##A Python library is a collection of pre-written code that you can use to perform common tasks without having to write the code from scratch. These libraries contain functions, classes, and modules that can be imported into your Python programs to provide additional functionality.

#Why We Use Python Libraries:
#Efficiency:

#Save Time: Libraries provide pre-written functions and classes, allowing you to avoid writing code from scratch.
#Code Reuse: Reuse existing, well-tested code, which can significantly speed up the development process.
#Functionality:

#Specialized Tools: Many libraries are designed for specific tasks such as data analysis, web development, machine learning, etc. For example, NumPy and pandas for data analysis, Flask and Django for web development, and TensorFlow and PyTorch for machine learning.
#Extended Capabilities: They extend the basic functionalities of Python, enabling you to accomplish more complex tasks that are not feasible with the standard library alone.
#Reliability:

#Well-Tested: Libraries, especially popular ones, are often well-tested and maintained by a community of developers, which ensures they are reliable and less prone to bugs.
#Community Support: Popular libraries have a large user base and community support, making it easier to find help, documentation, and tutorials.
#Consistency:

#Standard Practices: Libraries often follow standard practices and conventions, promoting consistency in your code.
#Maintenance: Using well-maintained libraries ensures that your codebase can stay updated with minimal effort.
#Examples of Popular Python Libraries:
#NumPy: For numerical computations and handling large multi-dimensional arrays and matrices.
#pandas: For data manipulation and analysis.
#Matplotlib: For data visualization and plotting.
#Requests: For making HTTP requests.
#Beautiful Soup: For web scraping and parsing HTML and XML documents.
#Flask and Django: For web development.
#TensorFlow and PyTorch: For machine learning and deep learning.
#How to Use Python Libraries:
#To use a library, you typically need to install it (if it's not included in the standard library) and then import it into your Python script. For example:

#python
#Copy code
# Installing a library (e.g., NumPy)
#!pip install numpy

# Importing and using the library
#import numpy as np

# Using a function from the NumPy library
#array = np.array([1, 2, 3])
#print(array)
#By using Python libraries, you leverage the collective knowledge and efforts of the programming community, enabling you to write more efficient, reliable, and maintainable code.

# What is the ^ifference between Numpy array an^ List?

#The primary differences between a NumPy array and a Python list revolve around performance, functionality, and usage. Here's a detailed comparison:

#1. Performance:
#NumPy Array: NumPy arrays are more efficient in terms of performance and memory usage, especially when dealing with large datasets. They are implemented in C and optimized for numerical computations, which allows for faster processing of data.
#Python List: Python lists are less efficient for numerical computations because they are implemented as dynamic arrays that store references to objects, resulting in higher memory usage and slower performance for numerical operations.
#2. Data Types:
#NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This uniformity allows NumPy to perform operations more efficiently.
#Python List: Python lists are heterogeneous, meaning they can contain elements of different data types. This flexibility can be useful, but it can also lead to inefficiencies in numerical operations.
#3. Functionality:
#NumPy Array:
#Mathematical Operations: NumPy supports a wide range of mathematical operations that can be performed directly on arrays, including element-wise operations, linear algebra, and statistical functions.
#Vectorization: Operations on NumPy arrays can be vectorized, allowing for batch processing of data without the need for explicit loops.
#Broadcasting: NumPy supports broadcasting, a powerful mechanism that allows operations on arrays of different shapes.
#Slicing and Indexing: NumPy provides advanced slicing and indexing capabilities, including boolean indexing and multi-dimensional slicing.
#Python List:
#General-Purpose Operations: Lists are versatile and can be used for a wide range of tasks beyond numerical computations, such as storing mixed data types and implementing various data structures.
#Built-In Methods: Lists have built-in methods for common operations like append, extend, and sort, but lack the extensive mathematical functions provided by NumPy.
#4. Memory Efficiency:
#NumPy Array: NumPy arrays are more memory-efficient because they store elements in contiguous memory blocks and use fixed-size data types.
#Python List: Lists are less memory-efficient because they store references to objects, which can lead to overhead due to dynamic typing and memory fragmentation.
#5. Use Cases:
#NumPy Array: Best suited for scientific computing, data analysis, and situations where performance and efficiency are critical, especially with large numerical datasets.
#Python List: Ideal for general-purpose programming tasks where flexibility and ease of use are more important than performance, and when working with mixed data types.

In [6]:
import numpy as n
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])


shape = array.shape
size = array.size
dimension = array.ndim

print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Dimension: {dimension}")

Shape: (3, 4)
Size: 12
Dimension: 2


In [7]:
import numpy as np


array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])


first_row = array[0]

print("First row:", first_row)

First row: [1 2 3 4]


In [11]:
import numpy as np


array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

:
element = array[2, 3]

print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [12]:
import numpy as np


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


odd_indexed_elements = arr[:, 1::2]

print(odd_indexed_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [13]:
import numpy as np


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


expanded_arr = np.expand_dims(arr, axis=0)

print("Original array shape:", arr.shape)
print("Expanded array shape:", expanded_arr.shape)
print(expanded_arr)

Original array shape: (3, 4)
Expanded array shape: (1, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [14]:
import numpy as np


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


transposed_arr = np.transpose(arr)

print(transposed_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [15]:
import numpy as np


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


transposed_arr = arr.T

print(transposed_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
import numpy as np

# Define Matrix A2
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Define Matrix B2
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#multiplication
elementwise_multiplication = A2 * B2


matrix_multiplication = np.dot(A2, B2.T) 
# Addition
addition = A2 + B2

# Subtraction
subtraction = A2 - B2

# Division (element-wise)
division = B2 / A2

print("Element-wise Multiplication:\n", elementwise_multiplication)
print("\nMatrix Multiplication:\n", matrix_multiplication)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nDivision (Element-wise):\n", division)

Element-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division (Element-wise):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
import numpy as np


arr = np.array([1, 2, 3, 4], dtype=np.int32)


swapped_arr = arr.byteswap()

print("Original array:", arr)
print("Swapped array:", swapped_arr)


Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


In [18]:
import numpy as np


arr = np.arange(12)


reshaped_arr = np.reshape(arr, (3, 4))

print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
import numpy as np


arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])


arr2 = np.array([10, 20, 30])


result = arr1 + arr2

print(result)

[[11 22 33]
 [14 25 36]]
